### ISSUE TITLE
Como a geração do HTML do site funciona?

### ISSUE THREAD

**Issue by JhonnyBn** [sergioSHKLR/doutrina.org#1]
Boa noite Sergio

Eu estava procurando pelos livros da codificação em formato texto (txt/md/json/etc) pra talvez criar um app simples de leitura contínua que salva onde parei e acabei encontrando esse belo projeto que pretende fazer justamente o que busco. Parabéns pela iniciativa e obrigado por compartilhar publicamente! 

Ao ver o readme percebi duas funções bem importantes marcadas com um V, que na minha interpretação significa que estão funcionais, porém ao ver o protótipo do site não consegui ler as partes dos livros. 

As funções que menciono são:
>  Capaz de construir HTML a partir do MD de origem. (pesquisando vários SSG)
>  Abrir o PDF da obra original

Segue print em que tento abrir um dos primeiros textos do livro dos espíritos
![image](https://user-images.githubusercontent.com/29382833/230998609-7432440c-1e40-4937-ba3e-f1a5928cfe0d.png)

Por acaso isso é um erro da minha parte que não entendi como abrir o texto, ou essas funções ainda estão em desenvolvimento? 
É o primeiro projeto SSG (server-side generator, correto?) que vejo e estou meio perdido. Aproveitando a pergunta, se já existe algo em desenvolvimento nessa parte, quais arquivos lidam com a criação do HTML do site? Mais especificamente a parte de clicar em um capítulo para mostrá-lo, e a parte que transforma os MDs em HTML para serem visualizados na tela lateral.

Gostaria de dar uma olhada e quem sabe talvez ajudar em algo.
Obrigado, João

**Comment by sergioSHKLR** [comment]
João, muito prazer e fico imensamente feliz de encontrar outros com a mesma intenção de estudar/disseminar a doutrina E com a capacidade programática de fazê-la! Eu sou um auto-didata mas num nível muito básico.

Este meu projeto já tem alguns anos e já tenho mais de 85 versões até hoje. Infelizmente, a versão mais completa, eu tive que tirar do ar por suspeita sobre o conteúdo principal (extraído de outro site). No momento eu estou manualmente copiando cada parágrafo do PDF original, limpando os line-breaks e outros caracteres e transpondo os trechos em itálico.

Atualmente eu tenho o LDE inteiro em formato MD e estou trabalhando para fazer os links do Indíce Geral.

Se estiver disponível para uma chamada de vídeo no Zoom, Meet oo Whatsapp, eu adoraria poder explicar o projeto. Meu email é sergio (arroba) shkrl.org e meu número no Whatsapp é +1 (sete dois sete) 877-9387.

Deus abençoe!

Sergio SHKLR
